
var games =
[
    {
        "division": "HSA",
        "gameid": 1,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A5",
        "field": 1,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 13,
        "team2id": 21,
        "team1name": "NV Ultimate A",
        "team2name": "HP Giants Ultimate",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 2,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A4",
        "field": 2,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 38,
        "team2id": 25,
        "team1name": "Gatortangs",
        "team2name": "Saint Charles East",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 3,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A4",
        "field": 1,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 13,
        "team2id": 25,
        "team1name": "NV Ultimate A",
        "team2name": "Saint Charles East",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 4,
        "pool": "A",
        "matchup1": "A3",
        "matchup2": "A5",
        "field": 2,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 7,
        "team2id": 21,
        "team1name": "Prtizker Jaguars",
        "team2name": "HP Giants Ultimate",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 5,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A3",
        "field": 1,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 13,
        "team2id": 7,
        "team1name": "NV Ultimate A",
        "team2name": "Prtizker Jaguars",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 6,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A5",
        "field": 2,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 38,
        "team2id": 21,
        "team1name": "Gatortangs",
        "team2name": "HP Giants Ultimate",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 7,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A2",
        "field": 1,
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 13,
        "team2id": 38,
        "team1name": "NV Ultimate A",
        "team2name": "Gatortangs",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 8,
        "pool": "A",
        "matchup1": "A3",
        "matchup2": "A4",
        "field": 2,
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 7,
        "team2id": 25,
        "team1name": "Prtizker Jaguars",
        "team2name": "Saint Charles East",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 9,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A3",
        "field": 1,
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 38,
        "team2id": 7,
        "team1name": "Gatortangs",
        "team2name": "Prtizker Jaguars",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 10,
        "pool": "A",
        "matchup1": "A4",
        "matchup2": "A5",
        "field": 2,
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 25,
        "team2id": 21,
        "team1name": "Saint Charles East",
        "team2name": "HP Giants Ultimate",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 11,
        "pool": "B",
        "matchup1": "B1",
        "matchup2": "B5",
        "field": 3,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 26,
        "team2id": 40,
        "team1name": "Geneva Vikings",
        "team2name": "Lane Tech",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 12,
        "pool": "B",
        "matchup1": "B2",
        "matchup2": "B4",
        "field": 4,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 14,
        "team2id": 47,
        "team1name": "NV Ultimate B",
        "team2name": "Elmhurst Evolution",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 13,
        "pool": "B",
        "matchup1": "B1",
        "matchup2": "B4",
        "field": 3,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 26,
        "team2id": 47,
        "team1name": "Geneva Vikings",
        "team2name": "Elmhurst Evolution",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 14,
        "pool": "B",
        "matchup1": "B3",
        "matchup2": "B5",
        "field": 4,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 22,
        "team2id": 40,
        "team1name": "Evanston Wildkits",
        "team2name": "Lane Tech",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 15,
        "pool": "B",
        "matchup1": "B1",
        "matchup2": "B3",
        "field": 3,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 26,
        "team2id": 22,
        "team1name": "Geneva Vikings",
        "team2name": "Evanston Wildkits",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 16,
        "pool": "B",
        "matchup1": "B2",
        "matchup2": "B5",
        "field": 4,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 14,
        "team2id": 40,
        "team1name": "NV Ultimate B",
        "team2name": "Lane Tech",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 17,
        "pool": "B",
        "matchup1": "B1",
        "matchup2": "B2",
        "field": 3,
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 26,
        "team2id": 14,
        "team1name": "Geneva Vikings",
        "team2name": "NV Ultimate B",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 18,
        "pool": "B",
        "matchup1": "B3",
        "matchup2": "B4",
        "field": 4,
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 22,
        "team2id": 47,
        "team1name": "Evanston Wildkits",
        "team2name": "Elmhurst Evolution",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 19,
        "pool": "B",
        "matchup1": "B2",
        "matchup2": "B3",
        "field": 3,
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 14,
        "team2id": 22,
        "team1name": "NV Ultimate B",
        "team2name": "Evanston Wildkits",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 20,
        "pool": "B",
        "matchup1": "B4",
        "matchup2": "B5",
        "field": 4,
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 47,
        "team2id": 40,
        "team1name": "Elmhurst Evolution",
        "team2name": "Lane Tech",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 21,
        "pool": "C",
        "matchup1": "C1",
        "matchup2": "C5",
        "field": 5,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 34,
        "team2id": 37,
        "team1name": "Naperville Central",
        "team2name": "Not Trier Ultimate",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 22,
        "pool": "C",
        "matchup1": "C2",
        "matchup2": "C4",
        "field": 6,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 46,
        "team2id": 43,
        "team1name": "Plainfield North",
        "team2name": "Metea Valley Mustangs",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 23,
        "pool": "C",
        "matchup1": "C1",
        "matchup2": "C4",
        "field": 5,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 34,
        "team2id": 43,
        "team1name": "Naperville Central",
        "team2name": "Metea Valley Mustangs",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 24,
        "pool": "C",
        "matchup1": "C3",
        "matchup2": "C5",
        "field": 6,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 10,
        "team2id": 37,
        "team1name": "Northstar Ultimate",
        "team2name": "Not Trier Ultimate",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 25,
        "pool": "C",
        "matchup1": "C1",
        "matchup2": "C3",
        "field": 5,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 34,
        "team2id": 10,
        "team1name": "Naperville Central",
        "team2name": "Northstar Ultimate",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 26,
        "pool": "C",
        "matchup1": "C2",
        "matchup2": "C5",
        "field": 6,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 46,
        "team2id": 37,
        "team1name": "Plainfield North",
        "team2name": "Not Trier Ultimate",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 27,
        "pool": "C",
        "matchup1": "C1",
        "matchup2": "C2",
        "field": 5,
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 34,
        "team2id": 46,
        "team1name": "Naperville Central",
        "team2name": "Plainfield North",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 28,
        "pool": "C",
        "matchup1": "C3",
        "matchup2": "C4",
        "field": 6,
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 10,
        "team2id": 43,
        "team1name": "Northstar Ultimate",
        "team2name": "Metea Valley Mustangs",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 29,
        "pool": "C",
        "matchup1": "C2",
        "matchup2": "C3",
        "field": 5,
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 46,
        "team2id": 10,
        "team1name": "Plainfield North",
        "team2name": "Northstar Ultimate",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 30,
        "pool": "C",
        "matchup1": "C4",
        "matchup2": "C5",
        "field": 6,
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 43,
        "team2id": 37,
        "team1name": "Metea Valley Mustangs",
        "team2name": "Not Trier Ultimate",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 31,
        "pool": "D",
        "matchup1": "D1",
        "matchup2": "D5",
        "field": 7,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 2,
        "team2id": 49,
        "team1name": "Fox Valley Fusion A",
        "team2name": "Lincoln-Way East Mirror Image",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 32,
        "pool": "D",
        "matchup1": "D2",
        "matchup2": "D4",
        "field": 8,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 35,
        "team2id": 41,
        "team1name": "OPRF Revolution",
        "team2name": "Naperville North",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 33,
        "pool": "D",
        "matchup1": "D1",
        "matchup2": "D4",
        "field": 7,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 2,
        "team2id": 41,
        "team1name": "Fox Valley Fusion A",
        "team2name": "Naperville North",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 34,
        "pool": "D",
        "matchup1": "D3",
        "matchup2": "D5",
        "field": 8,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 33,
        "team2id": 49,
        "team1name": "E'ville Elite ",
        "team2name": "Lincoln-Way East Mirror Image",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 35,
        "pool": "D",
        "matchup1": "D1",
        "matchup2": "D3",
        "field": 7,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 2,
        "team2id": 33,
        "team1name": "Fox Valley Fusion A",
        "team2name": "E'ville Elite ",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 36,
        "pool": "D",
        "matchup1": "D2",
        "matchup2": "D5",
        "field": 8,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 35,
        "team2id": 49,
        "team1name": "OPRF Revolution",
        "team2name": "Lincoln-Way East Mirror Image",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 37,
        "pool": "D",
        "matchup1": "D1",
        "matchup2": "D2",
        "field": 7,
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 2,
        "team2id": 35,
        "team1name": "Fox Valley Fusion A",
        "team2name": "OPRF Revolution",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 38,
        "pool": "D",
        "matchup1": "D3",
        "matchup2": "D4",
        "field": 8,
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 33,
        "team2id": 41,
        "team1name": "E'ville Elite ",
        "team2name": "Naperville North",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 39,
        "pool": "D",
        "matchup1": "D2",
        "matchup2": "D3",
        "field": 7,
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 35,
        "team2id": 33,
        "team1name": "OPRF Revolution",
        "team2name": "E'ville Elite ",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSA",
        "gameid": 40,
        "pool": "D",
        "matchup1": "D4",
        "matchup2": "D5",
        "field": 8,
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 41,
        "team2id": 49,
        "team1name": "Naperville North",
        "team2name": "Lincoln-Way East Mirror Image",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 1,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A3",
        "field": 9,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 3,
        "team2id": 39,
        "team1name": "Fox Valley Fusion B",
        "team2name": "Gatortangs- JV",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 2,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A4",
        "field": 10,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 17,
        "team2id": 29,
        "team1name": "NV Ultimate Gold",
        "team2name": "Geneva Vikings FS",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 3,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A4",
        "field": 9,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 3,
        "team2id": 29,
        "team1name": "Fox Valley Fusion B",
        "team2name": "Geneva Vikings FS",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 4,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A3",
        "field": 10,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 17,
        "team2id": 39,
        "team1name": "NV Ultimate Gold",
        "team2name": "Gatortangs- JV",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 5,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A2",
        "field": 9,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 3,
        "team2id": 17,
        "team1name": "Fox Valley Fusion B",
        "team2name": "NV Ultimate Gold",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 6,
        "pool": "A",
        "matchup1": "A3",
        "matchup2": "A4",
        "field": 10,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 39,
        "team2id": 29,
        "team1name": "Gatortangs- JV",
        "team2name": "Geneva Vikings FS",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 7,
        "pool": "B",
        "matchup1": "B1",
        "matchup2": "B3",
        "field": 11,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 1,
        "team2id": 44,
        "team1name": "Reavis Rams",
        "team2name": "Metea Valley Mustangs JV1",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 8,
        "pool": "B",
        "matchup1": "B2",
        "matchup2": "B4",
        "field": 12,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 36,
        "team2id": 45,
        "team1name": "OPRF Revolution Blue",
        "team2name": "Metea Valley Mustangs JV2",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 9,
        "pool": "B",
        "matchup1": "B1",
        "matchup2": "B4",
        "field": 11,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 1,
        "team2id": 45,
        "team1name": "Reavis Rams",
        "team2name": "Metea Valley Mustangs JV2",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 10,
        "pool": "B",
        "matchup1": "B2",
        "matchup2": "B3",
        "field": 12,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 36,
        "team2id": 44,
        "team1name": "OPRF Revolution Blue",
        "team2name": "Metea Valley Mustangs JV1",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 11,
        "pool": "B",
        "matchup1": "B1",
        "matchup2": "B2",
        "field": 11,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 1,
        "team2id": 36,
        "team1name": "Reavis Rams",
        "team2name": "OPRF Revolution Blue",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 12,
        "pool": "B",
        "matchup1": "B3",
        "matchup2": "B4",
        "field": 12,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 44,
        "team2id": 45,
        "team1name": "Metea Valley Mustangs JV1",
        "team2name": "Metea Valley Mustangs JV2",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 13,
        "pool": "C/D",
        "matchup1": "C1",
        "matchup2": "C3",
        "field": 13,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 6,
        "team2id": 11,
        "team1name": "Colossus of Latin",
        "team2name": "Northstar Ultimate JV",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 14,
        "pool": "C/D",
        "matchup1": "C2",
        "matchup2": "D2",
        "field": 14,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 16,
        "team2id": 15,
        "team1name": "NV Ultimate Blue",
        "team2name": "NV Ultimate Bravo",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 15,
        "pool": "C/D",
        "matchup1": "D1",
        "matchup2": "D3",
        "field": 15,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 32,
        "team2id": 28,
        "team1name": "Downers Grove South",
        "team2name": "Geneva Vikings JV",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 16,
        "pool": "C/D",
        "matchup1": "C1",
        "matchup2": "D3",
        "field": 13,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 6,
        "team2id": 28,
        "team1name": "Colossus of Latin",
        "team2name": "Geneva Vikings JV",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 17,
        "pool": "C/D",
        "matchup1": "C2",
        "matchup2": "C3",
        "field": 14,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 16,
        "team2id": 11,
        "team1name": "NV Ultimate Blue",
        "team2name": "Northstar Ultimate JV",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 18,
        "pool": "C/D",
        "matchup1": "D1",
        "matchup2": "D2",
        "field": 15,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 32,
        "team2id": 15,
        "team1name": "Downers Grove South",
        "team2name": "NV Ultimate Bravo",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 19,
        "pool": "C/D",
        "matchup1": "C1",
        "matchup2": "C2",
        "field": 13,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 6,
        "team2id": 16,
        "team1name": "Colossus of Latin",
        "team2name": "NV Ultimate Blue",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 20,
        "pool": "C/D",
        "matchup1": "D1",
        "matchup2": "C3",
        "field": 14,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 32,
        "team2id": 11,
        "team1name": "Downers Grove South",
        "team2name": "Northstar Ultimate JV",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSB",
        "gameid": 21,
        "pool": "C/D",
        "matchup1": "D2",
        "matchup2": "D3",
        "field": 15,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 15,
        "team2id": 28,
        "team1name": "NV Ultimate Bravo",
        "team2name": "Geneva Vikings JV",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSA",
        "gameid": 1,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A5",
        "field": "MS1",
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 18,
        "team2id": 48,
        "team1name": "NV Youth A",
        "team2name": "Lake Bluff MS",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSA",
        "gameid": 2,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A4",
        "field": "MS2",
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 4,
        "team2id": 42,
        "team1name": "Fox Valley Fusion A",
        "team2name": "Julian Jayhawks",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSA",
        "gameid": 3,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A4",
        "field": "MS1",
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 18,
        "team2id": 42,
        "team1name": "NV Youth A",
        "team2name": "Julian Jayhawks",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSA",
        "gameid": 4,
        "pool": "A",
        "matchup1": "A3",
        "matchup2": "A5",
        "field": "MS2",
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 30,
        "team2id": 48,
        "team1name": "Geneva Vikings A",
        "team2name": "Lake Bluff MS",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSA",
        "gameid": 5,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A3",
        "field": "MS1",
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 18,
        "team2id": 30,
        "team1name": "NV Youth A",
        "team2name": "Geneva Vikings A",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSA",
        "gameid": 6,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A5",
        "field": "MS2",
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 4,
        "team2id": 48,
        "team1name": "Fox Valley Fusion A",
        "team2name": "Lake Bluff MS",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSA",
        "gameid": 7,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A2",
        "field": "MS1",
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 18,
        "team2id": 4,
        "team1name": "NV Youth A",
        "team2name": "Fox Valley Fusion A",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSA",
        "gameid": 8,
        "pool": "A",
        "matchup1": "A3",
        "matchup2": "A4",
        "field": "MS2",
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 30,
        "team2id": 42,
        "team1name": "Geneva Vikings A",
        "team2name": "Julian Jayhawks",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSA",
        "gameid": 9,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A3",
        "field": "MS1",
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 4,
        "team2id": 30,
        "team1name": "Fox Valley Fusion A",
        "team2name": "Geneva Vikings A",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSA",
        "gameid": 10,
        "pool": "A",
        "matchup1": "A4",
        "matchup2": "A5",
        "field": "MS2",
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 42,
        "team2id": 48,
        "team1name": "Julian Jayhawks",
        "team2name": "Lake Bluff MS",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSB",
        "gameid": 1,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A5",
        "field": "MS3",
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 12,
        "team2id": 31,
        "team1name": "Haines Hurricane Ultimate",
        "team2name": "Geneva Vikings B",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSB",
        "gameid": 2,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A4",
        "field": "MS4",
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 5,
        "team2id": 20,
        "team1name": " Fox Valley Fusion ",
        "team2name": "NV Youth Y",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSB",
        "gameid": 3,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A4",
        "field": "MS3",
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 12,
        "team2id": 20,
        "team1name": "Haines Hurricane Ultimate",
        "team2name": "NV Youth Y",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSB",
        "gameid": 4,
        "pool": "A",
        "matchup1": "A3",
        "matchup2": "A5",
        "field": "MS4",
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 19,
        "team2id": 31,
        "team1name": "NV Youth X",
        "team2name": "Geneva Vikings B",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSB",
        "gameid": 5,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A3",
        "field": "MS3",
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 12,
        "team2id": 19,
        "team1name": "Haines Hurricane Ultimate",
        "team2name": "NV Youth X",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSB",
        "gameid": 6,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A5",
        "field": "MS4",
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 5,
        "team2id": 31,
        "team1name": " Fox Valley Fusion ",
        "team2name": "Geneva Vikings B",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSB",
        "gameid": 7,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A2",
        "field": "MS3",
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 12,
        "team2id": 5,
        "team1name": "Haines Hurricane Ultimate",
        "team2name": " Fox Valley Fusion ",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSB",
        "gameid": 8,
        "pool": "A",
        "matchup1": "A3",
        "matchup2": "A4",
        "field": "MS4",
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 19,
        "team2id": 20,
        "team1name": "NV Youth X",
        "team2name": "NV Youth Y",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSB",
        "gameid": 9,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A3",
        "field": "MS3",
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 5,
        "team2id": 19,
        "team1name": " Fox Valley Fusion ",
        "team2name": "NV Youth X",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "MSB",
        "gameid": 10,
        "pool": "A",
        "matchup1": "A4",
        "matchup2": "A5",
        "field": "MS4",
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 20,
        "team2id": 31,
        "team1name": "NV Youth Y",
        "team2name": "Geneva Vikings B",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSG",
        "gameid": 1,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A5",
        "field": 16,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 23,
        "team2id": 8,
        "team1name": "eNVy X",
        "team2name": "Pritzker Lady Jaguars",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSG",
        "gameid": 2,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A4",
        "field": 17,
        "starttime": "9:00",
        "endtime": "10:15",
        "team1id": 24,
        "team2id": 27,
        "team1name": "eNVy Y",
        "team2name": "Geneva Vikings Girls",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSG",
        "gameid": 3,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A4",
        "field": 16,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 23,
        "team2id": 27,
        "team1name": "eNVy X",
        "team2name": "Geneva Vikings Girls",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSG",
        "gameid": 4,
        "pool": "A",
        "matchup1": "A3",
        "matchup2": "A5",
        "field": 17,
        "starttime": "10:30",
        "endtime": "11:45",
        "team1id": 9,
        "team2id": 8,
        "team1name": "Walter Payton Grizzlies",
        "team2name": "Pritzker Lady Jaguars",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSG",
        "gameid": 5,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A3",
        "field": 16,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 23,
        "team2id": 9,
        "team1name": "eNVy X",
        "team2name": "Walter Payton Grizzlies",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSG",
        "gameid": 6,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A5",
        "field": 17,
        "starttime": "12:00",
        "endtime": "1:15",
        "team1id": 24,
        "team2id": 8,
        "team1name": "eNVy Y",
        "team2name": "Pritzker Lady Jaguars",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSG",
        "gameid": 7,
        "pool": "A",
        "matchup1": "A1",
        "matchup2": "A2",
        "field": 16,
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 23,
        "team2id": 24,
        "team1name": "eNVy X",
        "team2name": "eNVy Y",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSG",
        "gameid": 8,
        "pool": "A",
        "matchup1": "A3",
        "matchup2": "A4",
        "field": 17,
        "starttime": "1:30",
        "endtime": "2:45",
        "team1id": 9,
        "team2id": 27,
        "team1name": "Walter Payton Grizzlies",
        "team2name": "Geneva Vikings Girls",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSG",
        "gameid": 9,
        "pool": "A",
        "matchup1": "A2",
        "matchup2": "A3",
        "field": 16,
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 24,
        "team2id": 9,
        "team1name": "eNVy Y",
        "team2name": "Walter Payton Grizzlies",
        "team1score": 0,
        "team2score": 0
    },
    {
        "division": "HSG",
        "gameid": 10,
        "pool": "A",
        "matchup1": "A4",
        "matchup2": "A5",
        "field": 17,
        "starttime": "3:00",
        "endtime": "4:15",
        "team1id": 27,
        "team2id": 8,
        "team1name": "Geneva Vikings Girls",
        "team2name": "Pritzker Lady Jaguars",
        "team1score": 0,
        "team2score": 0
    }
];

var countHSA = 0;
var countHSB = 0;
var countHSG = 0;
var countMSA = 0;
var countMSB = 0;
for(var i=0; i<games.length;i++){
    if(games[i].division == "HSA"){
        countHSA++;
    } else if(games[i].division == "HSB"){
        countHSB++;
    } else if(games[i].division == "HSG"){
        countHSG++;
    } else if(games[i].division == "MSA"){
        countMSA++;
    } else{
        countMSB++;
    }
}

var gamesHSA = new Array(countHSA);
var gamesHSB = new Array(countHSB);
var gamesHSG = new Array(countHSG);
var gamesMSA = new Array(countMSA);
var gamesMSB = new Array(countMSB);

var placeHSA = 0, placeHSB = 0, placeHSG = 0, placeMSA = 0, placeMSB = 0;

for(var i=0; i<games.length;i++){
    if(games[i].division == "HSA"){
        gamesHSA[placeHSA] = games[i];
        placeHSA++;
    } else if(games[i].division == "HSB"){
        gamesHSB[placeHSB] = games[i];
        placeHSB++;
    } else if(games[i].division == "HSG"){
        gamesHSG[placeHSG] = games[i];
        placeHSG++;
    } else if(games[i].division == "MSA"){
        gamesMSA[placeMSA] = games[i];
        placeMSA++;
    } else{
        gamesMSB[placeMSB] = games[i];
        placeMSB++;
    }
}

